package com.rmlocacoes.rmlocacoes.util;

public class TemplateEmail {

  public String getTemplateContrato() {
    StringBuffer msg = new StringBuffer();
    msg.append("<body>")
       .append("<h1 style=\"text-align: center;\">Contrato de Locação</h1>")
       .append("<div style='display: flex; flex-direction: row;'>")
       .append("<div style='flex: auto;'>")
       .append("Locador:")
       .append("<span>RM Locações</span>")
       .append("</div>")
       .append("<div style='flex: auto;'>")
       .append("<span>AV. Judéia n° 567 Bairro Canaã</span>")
       .append("</div>")
       .append("<div style='flex: auto;'>")
       .append("<span>Fone: (034) 3237-5780</span>")
       .append("</div>")
       .append("</div>")
       .append("<br />")
       .append("<div style='display: flex; flex-direction: row;'>")
       .append("<div style='flex: auto;'>Locatário:")
       .append("<span>locatario.cliente.nome</span>/ {{tipoDoc}}:")
       .append("<span>locatario.cliente.documento</span> ")
       .append("</div>")
       .append("<div style='flex: auto;'>")
       .append("<span>locatario.enderecoContrato.logradouro</span> - Bairro:")
       .append("<span>locatario.enderecoContrato.bairro</span>")
       .append("</div>")
       .append("<div style='flex: auto;'>")
       .append("<span>Fones: locatario.cliente.teleFoneCelular{{locatario.cliente.teleFoneFixo}}</span>")
       .append("</div>")
       .append("</div>")
       .append("<br />")
       .append("<div style='display: flex; flex-direction: row;'")
       .append("<div style='flex: auto;'>")
       .append("Data da Entrega: ")
       .append("<span>locatario.dtaEntrega</span>")
       .append("</div>")
       .append("<br />")
       .append("<div style='flex: auto;'>")
       .append("Data da Devolução: ")
       .append("<span>locatario.dtaDevolucao</span>")
       .append("</div>")
       .append("</div>")
       .append("<br />")
       .append("<div style='display: flex; flex-direction: row;'>")
       .append("<p>1 - Neste ato, as partes firmam o presente contrato delocação de bens móveis com duracação de quatro dias conforme")
       .append("artigos 1.188 a 1.199 do código Civil Brasileiro, sendo que os bens serão entregues pelo Locatário dia, locatario.dtaEntrega</p>")
       .append("</div>")
       .append("<div style='display: flex; flex-direction: row;'>")
       .append("<p>2 - O Locatário acima qualificado, ou pessoa por eledesignada recebe em locação os bens abaixo descriminados.</p>")
       .append("</div>")
       .append("<div>")
       .append("<table style='table-layout: fixed; width: 100%; border-collapse: collapse; border: 3px solid rgb(223, 219, 223);'")
       .append("<thead>")
       .append("<tr>")
       .append("<th>Produto</th>")
       .append("<th>Preço</th>")
       .append("<th>Quantidade</th>")
       .append("<th>Total</th>")
       .append("</tr>")
       .append("</thead>")
       .append("<tbody>")
       .append("{{itens}}")
       .append("<tr>")
       .append("<td style='background-color: #ffebee'>Frete: contrato.pagamento.vlrTxEntrega</td>")
       .append("<td style='background-color: #ffebee'>Total Revenda: contrato.totalProdutos</td>")
       .append("<td style='background-color: #ffebee'>Total Comodato: contrato.totalComodato</td>")
       .append("<td style='background-color: #ffebee'>Total do Pedido: contrato.totalPedido</td>")
       .append("</tr>")
       .append("</tbody>")
       .append("</table>")
       .append("</div>")
       .append("<div style='display: flex; flex-direction: row;'>")
       .append("<p>3 - O locatário após a vistoria de entrega, declara nesteato, que recebeu todo o material em perfetio estado")
       .append("de usu e conservação, ficando ainda, após o usu, obrigado a efetuar a reposição imediata dos bens danificados,")
       .append("da mesma marca e modelo, sendo que caso não haja no mercado o mesmo produto, devera o locador indicar quais")
       .append("marcas e modelos que aceita como reposição.</p>")
       .append("</div>")
       .append("<div style='display: flex; flex-direction: row;'>")
       .append("<p>4 - Os bens locados deverão ser devolvidos no vencimentodeste, e caso o locatário não entregues os bens na data")
       .append("combinada, a locação passará a ser diária e seu valor de acordocom a tabela acima, podendo o locador tomar")
       .append("medidas necessárias para a recuperação dos bens locados, sem prejuízo do aluguel pelo período de atraso.</p>")
       .append("</div>")
       .append("<div style='display: flex; flex-direction: row;'>")
       .append("<div id=\"dtaContrato\" style='flex: auto;'>")
       .append("Uberlândia, ")
       .append("<span>dtaContrato</span>")
       .append("</div>")
       .append("</div>")
       .append("<div style='width: 100%;  margin-top: 40px;'>")
       .append("<div style='border-bottom: 1px solid black; width: 47%; float: left;'>Locador:</div>")
       .append("<div style='border-bottom: 1px solid black; width: 47%; float: left; margin-left: 2%;'>Locatario:</div>")
       .append("</div>")
       .append("<div style='width: 100%; margin-top: 100px;'>")
       .append("<div style='border-bottom: 1px solid black; width: 47%; float: left;'>Entregue:</div>")
       .append("<div style='border-bottom: 1px solid black; width: 47%; float: left; margin-left: 2%;'>Pago:</div>")

       .append("</div>")
       .append("<div style='width: 100%; margin-top: 160px;'>")
       .append("<div style='border-bottom: 1px solid black; width: 96%; float: left;;'>(Obs) Coletado:</div>")
       .append("</div>")
       .append("</body>");

    return msg.toString();
  }

}
